### ISSUE TITLE
company-mode color contrast too low

### ISSUE THREAD

**Issue by ydzhou** [meritamen/emacs-kanagawa-theme#5]
Can you help increase the contrast of highlighted one?

<img width="773" alt="Screenshot 2024-03-19 at 2 16 03 AM" src="https://github.com/meritamen/emacs-kanagawa-theme/assets/3310714/423bf7e7-5eba-4085-be28-d919186aa96b">

**Comment by meritamen** [comment]
Hello, @ydzhou. You could customize faces like below
```
(define-kanagawa-dark-theme
 'kanagawa
 `(company-tooltip-selection ((,class (:background ,fuji-gray :foreground ,winter-red :weight bold)))))
```
