### ISSUE TITLE
Symbol’s value as variable is void: kanagawa-dark-palette

### ISSUE THREAD

**Issue by nestoremgi** [meritamen/emacs-kanagawa-theme#7]
Hi! I download theme from MELPA with command package-install kanagawa-theme and when it finished it shows this. I don't know how to solve it. I think it works parcial but I don't sure if it is a expect behaivor or I miss configure something. Thanks!

<img width="526" alt="image" src="https://github.com/meritamen/emacs-kanagawa-theme/assets/105574612/461930d6-4ab2-4bf0-bdf0-3c63c1d30086">

**Comment by meritamen** [comment]
Fixed in #8
