### ISSUE TITLE
Strange appearance on tty mode

### ISSUE THREAD

**Issue by PyB1l** [meritamen/emacs-kanagawa-theme#9]
Hi there, when running emacs on with -nw flag the theme seems ti be almost grey everywhere, it looks almost like
there is no syntax highinting.

**Comment by meritamen** [comment]
Hello @PyB1l, I had a test in my terminal and it works out, I seldom use emacs with -nw flag so that I don't know a lot about tty, but I guess your terminal maybe don't support true color?

<img width="1002" alt="Screenshot 2024-04-28 at 20 43 03" src="https://github.com/meritamen/emacs-kanagawa-theme/assets/136421664/f678fe53-19f4-4a94-865b-3cac6ab902c8">

**Comment by PyB1l** [comment]
You are probably right, but to be more precise I am facing the 
issue with emacsclient -nw and not emacs -nw

**Comment by PyB1l** [comment]
I am using kitty as term emulator and  true colors are supported - the emacs -nw works ok -  but when connecting to emacs server with emacsclient -nw I still have the issue.

**Comment by meritamen** [comment]
@PyB1l I added the following code then it works out for me.
```(setq default-frame-alist '((tty-color-mode . true-color)))```
<img width="1019" alt="Screenshot 2024-04-28 at 23 36 09" src="https://github.com/meritamen/emacs-kanagawa-theme/assets/136421664/4a199c50-8dad-41cd-835f-dc1f2df4cdf7">

**Comment by meritamen** [comment]
@PyB1l Is your issue resolved now?

**Comment by PyB1l** [comment]
Hi, I have managed to make it work for kitty term, but now I am facing another weird behavior when running 
emacsclient inside tmux.

Any thoughts?

Thanks in advance

**Comment by meritamen** [comment]
I found something that probably works.
https://mbuffett.com/posts/setting-up-tmux-and-kitty-for-true-color-support/

**Comment by PyB1l** [comment]
I already have these settings but no luck there.
In any case the plain emacs works fine, you can close this issue and I if a have any updates I will leave a comment here
